### ISSUE TITLE
Docs or code examples?

### ISSUE THREAD

**Issue by elvismdev** [rahuljayaraman/doctrine-graphql#1]
Hi,
 
Is there any example code around I can follow on how to use this package and map my Doctrine entities to a GraphQL endpoint?

I have an existing Silex application that uses doctrine entity manager to work with a single MySQL database with two tables/entities so far.

Found this other [package](https://github.com/Youshido/silex-graphql) which seems to do all I need to have a `/graphql` endpoint in my Silex app, but [still not clear yet](https://github.com/Youshido/silex-graphql/issues/1) how to put the whole thing together within my existing code. Found [this other conversation](https://github.com/webonyx/graphql-php/issues/103#issuecomment-309829454) and I have the feeling that this package `rahuljayaraman/doctrine-graphql` can help me to create the GraphQL schema I need to use `Youshido/silex-graphql` in my Silex project. 

Is this correct? If so, could you give me an example code on how can I build my GraphQL schema out of this doctrine entity using `rahuljayaraman/doctrine-graphql`?

```php
// Set the doctrine entity manager.
$em = $this->app['orm.em'];
// Get orders repository/entity.
$orders = $em->getRepository( 'Vendor\Package\Entity\Orders' );
```

Thank you,

**Comment by rahuljayaraman** [comment]
Hey,

I'll try & put up some documentation this week. 

Was trying to solve a similar problem (ie. use my existing schema without any massive rewrites). This lib is built on top of [webonyx/graphql-php](webonyx/graphql-php). It maps your doctrine entities to an [ObjectType](http://webonyx.github.io/graphql-php/type-system/object-types/) graph at runtime. (The mapper recursively looks for associations & builds the graph). 

IMO, this works well with other higher level graphQL packages. For eg: I use it along with [Folkloreatelier/laravel-graphql](https://github.com/Folkloreatelier/laravel-graphql) as of now which helped me setup REST endpoints, graphQL root nodes etc.

Here's a high level example, based on how I use it.
```php
//Setup code, I use this in a laravel service provider
use RahulJayaraman\DoctrineGraphQL\Mapper;
use Folklore\GraphQL\Support\Facades\GraphQL;

....
        Mapper::setup(
            app(EntityManager::class),
            function ($typeName, $type) {
                GraphQL::addType($type, $typeName);
            },
            function ($typeName) {
                return GraphQL::type($typeName);
            }
        );
```
The 2nd & the 3rd argument are setter & getter methods to laravel-graphql's store (a data structure which caches types).

To extract the type, one could use. [related doc](https://github.com/Folkloreatelier/laravel-graphql#creating-a-query)
```php
public function type()
{
     return Mapper::extractType(Entity::class);
}
```

Let's assume my entity graph is like this,

User => Employee => Company => Policies etc.

Registering the root node, builds the above map for you.

One can include additional fields or blacklist current ones using a couple of annotations.
```php
use RahulJayaraman\DoctrineGraphQL\Annotations\RegisterField;
use RahulJayaraman\DoctrineGraphQL\Annotations\BlacklistField;

  /**
     * @var string
     * @ORM\Column(type="string", nullable=true)
     * @BlacklistField()
     */
    private $password;

 /**
     * getEmployee
     *
     * @RegisterField(type="Employee", args={{"slug", "string"}})
     */
    public function getEmployee($slug)
    {
        return ...
    }
```
I'll try and elaborate further with more examples in the README.

Also, there are some missing features, which i plan to add this week.

Lastly, this repo is still work in progress & the code is still in flux, things 'might' change over the couple of weeks

Cheers!

**Comment by rahuljayaraman** [comment]
I've updated the readme with some docs. Do ping me/open additional issues with feedback.
